### ISSUE TITLE
_Generic failing on function types and literal string

### ISSUE THREAD

**Issue by thradams** [PascalBeyer/Headerless-C-Compiler#2]
This program should compile with no errors

```c
int main(void)
{
    _Static_assert(_Generic(main, int (*)(void) : 1 ), "");
    _Static_assert(_Generic("abc",  char *: 1), "");    
}
```
https://godbolt.org/z/d6zvh13KG

hlc is giving

Error at '_Generic': _Generic choice did not match any of the associations.
Error at '_Generic': _Generic choice did not match any of the associations.

**Comment by thradams** [comment]
The problem with the literal string is that it is not doing lvalue conversion.

I checked with this sample

```c
  _Static_assert(_Generic("abc",  char [4]: 1), "");    
```
that is not giving any error.(it should)
https://godbolt.org/z/o8q58o3Gz

**Comment by PascalBeyer** [comment]
Thanks for the report! I have fixed it and pushed a commit to 'main' :)
